### ISSUE TITLE
Why does cursor position advance forward after each save when using e.g. pg_format on the .sql...

### ISSUE THREAD

**Issue by 0pdd** [frou/PreSaveFormat#7]
The puzzle `0-afaf0480` from #0 has to be resolved: 

https://github.com/frou/PreSaveFormat/blob/60a590896bb201c529834df89c33b108a42c1a81/src/format.py#L15-L23

The puzzle was created by Duncan Holm on 27-May-20. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by frou** [comment]
Someone else encountered similar thing? https://github.com/llvm-mirror/clang/blob/master/tools/clang-format/clang-format-sublime.py#L58
